---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  phpcodesniffer:
    enabled: true
    config:
      ignore_warnings: true
ratings:
  paths:
  - "**.php"
exclude_paths:
- tests/
- vendor/
